---

- name: "prepare postgres ssl hosts list"
  hosts: apollo.archlinux.org
  tasks:
      - name: assign ipv4 addresses to fact postgres_ssl_hosts4
        set_fact: postgres_ssl_hosts4="{{ [gemini4] + detected_ips }}"
        vars:
            gemini4: "{{ hostvars['gemini.archlinux.org']['ipv4_address'] }}/32"
            detected_ips: "{{ groups['mirrors'] | map('extract', hostvars, ['ipv4_address']) | select() | map('regex_replace', '^(.+)$', '\\1/32') | list }}"
        tags: ["postgres", "firewall"]
      - name: assign ipv6 addresses to fact postgres_ssl_hosts6
        set_fact: postgres_ssl_hosts6="{{ [gemini6] + detected_ips }}"
        vars:
            gemini6: "{{ hostvars['gemini.archlinux.org']['ipv6_address'] }}/128"
            detected_ips: "{{ groups['mirrors'] | map('extract', hostvars, ['ipv6_address']) | select() | map('regex_replace', '^(.+)$', '\\1/128') | list }}"
        tags: ["postgres", "firewall"]

- name: setup apollo
  hosts: apollo.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg_client, tags: ["borg"] }
    - { role: certbot }
    - { role: nginx }
    - { role: rspamd, tags: ["mail"] }
    - { role: unbound, tags: ["mail"] }
    - { role: postfix, postfix_relayhost: "mail.archlinux.org", postfix_smtpd_public: true, postfix_patchwork_enabled: true, tags: ["mail"] }
    - { role: opendkim, dkim_selector: apollo, tags: ['mail'] }
    - { role: postfwd, tags: ['mail'] }
    - role: postgres
      postgres_listen_addresses: "*"
      postgres_max_connections: 1000
      postgres_ssl: 'on'
      postgres_shared_buffers: 4096MB
    - { role: mariadb, mariadb_query_cache_type: '0', mariadb_innodb_file_per_table: True }
    - { role: sudo }
    - { role: uwsgi }
    - { role: php_fpm, php_extensions: ['bcmath', 'curl', 'gd', 'iconv', 'intl', 'mysqli', 'pdo_pgsql', 'pgsql', 'sockets', 'zip'], zend_extensions: ['opcache'] }
    - { role: memcached }
    - { role: archweb, archweb_planet: true }
    - role: security_tracker
      security_tracker_domain: "security.archlinux.org"
      security_tracker_nginx_conf: '/etc/nginx/nginx.d/security-tracker.conf'
      security_tracker_dir: "/srv/http/security-tracker"
    - { role: mailman, mailman_domain: "lists.archlinux.org" }
    - { role: patchwork }
    - { role: kanboard }
    - { role: zabbix_server, tags: ["zabbix"] }
    - { role: grafana }
    - { role: archwiki }
    - { role: conf_archlinux }
    - { role: fail2ban }
