---

- name: common playbook for rebuilderd_workers
  hosts: rebuilderd_workers
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: unbound }
    - { role: root_ssh }
    - { role: rebuilderd_worker }
    - { role: prometheus_exporters }
    - { role: fail2ban }
